FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o frontend .

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/frontend .
COPY --from=builder /app/kodata ./kodata
EXPOSE 8080
CMD ["./frontend"]
